### ISSUE TITLE
Can't launch server with mod [1.18.2]

### ISSUE THREAD

**Issue by Proxwian** [baka-gourd/LogUnSpam#2]
[25Nov2022 20:08:14.523] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.1.84, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[25Nov2022 20:08:14.525] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.5 by BellSoft
[25Nov2022 20:08:14.662] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/mcserver/magma/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[25Nov2022 20:08:15.108] [main/FATAL] [net.minecraftforge.forgespi.language.MavenVersionAdapter/]: Failed to parse version spec [1.18)
org.apache.maven.artifact.versioning.InvalidVersionSpecificationException: Single version must be surrounded by []: [1.18)
	at org.apache.maven.artifact.versioning.VersionRange.parseRestriction(VersionRange.java:203) ~[maven-artifact-3.6.3.jar%239!/:3.6.3]
	at org.apache.maven.artifact.versioning.VersionRange.createFromVersionSpec(VersionRange.java:145) ~[maven-artifact-3.6.3.jar%239!/:3.6.3]
	at net.minecraftforge.forgespi.language.MavenVersionAdapter.createFromVersionSpec(MavenVersionAdapter.java:33) ~[forgespi-4.0.15-4.x.jar%233!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo$ModVersion.<init>(ModInfo.java:178) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.lambda$new$6(ModInfo.java:80) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.lambda$new$7(ModInfo.java:81) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.<init>(ModInfo.java:78) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:69) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.<init>(ModFileInfo.java:70) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:47) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:79) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:68) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractModLocator.createMod(AbstractModLocator.java:49) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:23) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:26) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:59) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:1.0]
	at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:1.0]
	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100) ~[modlauncher-9.1.3.jar%235!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) [?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) [?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) [?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) [?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) [?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:87) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

**Comment by baka-gourd** [comment]
[log_un_spam-1.0-1.18.zip](https://github.com/baka-gourd/LogUnSpam/files/10095539/log_un_spam-1.0-1.18.zip)
try this

**Comment by Proxwian** [comment]
[04:13:52] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: class com.nullpinter.logUnSpam.util.ConfigHandler onModConfigEvent(Lnet/minecraftforge/fml/event/config/ModConfigEvent;)V
java.lang.UnsupportedOperationException
        at java.base/java.util.Collections$1.remove(Collections.java:4820)
        at java.base/java.util.AbstractCollection.remove(AbstractCollection.java:283)
        at TRANSFORMER/log_un_spam@1.0-1.18/com.nullpinter.logUnSpam.util.ConfigHandler.bakeConfig(ConfigHandler.java:46)
        at TRANSFORMER/log_un_spam@1.0-1.18/com.nullpinter.logUnSpam.util.ConfigHandler.onModConfigEvent(ConfigHandler.java:54)
        at net.minecraftforge.eventbus.ASMEventHandler_1488_ConfigHandler_onModConfigEvent_ModConfigEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.84/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:41)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:135)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:135)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50)
        at TRANSFORMER/forge@40.1.84/net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:34)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:186)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:186)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:170)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.84/net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:170)
        at TRANSFORMER/forge@40.1.84/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:33)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.84/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

[04:13:52] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
java.lang.UnsupportedOperationException: null
        at java.util.Collections$1.remove(Collections.java:4820) ~[?:?] {}
        at java.util.AbstractCollection.remove(AbstractCollection.java:283) ~[?:?] {re:computing_frames,re:mixin}
        at com.nullpinter.logUnSpam.util.ConfigHandler.bakeConfig(ConfigHandler.java:46) ~[log_un_spam-1.0-1.18-2.jar%23180!/:1.0-1.18] {re:classloading}
        at com.nullpinter.logUnSpam.util.ConfigHandler.onModConfigEvent(ConfigHandler.java:54) ~[log_un_spam-1.0-1.18-2.jar%23180!/:1.0-1.18] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_1488_ConfigHandler_onModConfigEvent_ModConfigEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:41) ~[javafmllanguage-1.18.2-40.1.84.jar%23291!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:135) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:135) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:34) ~[forge-1.18.2-40.1.84-universal.jar%23294!/:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:170) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:170) ~[fmlcore-1.18.2-40.1.84.jar%23290!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:33) ~[forge-1.18.2-40.1.84-universal.jar%23294!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by baka-gourd** [comment]
What is your server version? forge or catserver etc.

**Comment by Proxwian** [comment]
Forge 40.1.85/40.1.84

**Comment by GBLodb** [comment]
Fixed in [fc39d23](https://github.com/baka-gourd/LogUnSpam/commit/fc39d23a8134d22ecc5e9f57bd43c165128bcb3f).

**Comment by loldev69** [comment]
@GBLodb you forgot to release a version with this fix included.

**Comment by baka-gourd** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/logunspam/files/4386488

**Comment by loldev69** [comment]
Whoops, I was looking at the modrinth page
